# Generated by Django 2.1.1 on 2018-09-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='score',
            field=models.IntegerField(default=1),
        ),
    ]
